version: "3.8"

services:
  doc_server:
    container_name: doc_server
    hostname: doc_server
    image: doc_server
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '8080:8080'
      - '8085:8085'
    env_file:
      - docker/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    build:
      context: .
      dockerfile: docker/pg/Dockerfile
    environment:
      POSTGRES_PASSWORD: abcde12345
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata: